# Generated by Django 4.1.4 on 2023-01-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0003_statprofile_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statprofile',
            name='charge_stat',
            field=models.BooleanField(default=False),
        ),
    ]
