# Generated by Django 4.1.4 on 2023-01-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0006_remove_statprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='statprofile',
            name='uid',
            field=models.IntegerField(default=0),
        ),
    ]
