# Generated by Django 4.1.4 on 2023-03-15 06:59

import charge.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charge", "0007_statprofile_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="statprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 3, 15, 6, 59, 8, 207376, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="statprofile",
            name="cid",
            field=models.CharField(
                default=charge.models.generate_code, max_length=8, unique=True
            ),
        ),
    ]
