# Generated by Django 4.1.4 on 2023-03-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charge", "0008_statprofile_created_at_alter_statprofile_cid"),
    ]

    operations = [
        migrations.AddField(
            model_name="statprofile",
            name="op",
            field=models.CharField(default="", max_length=100),
        ),
    ]
