# Generated by Django 4.1.4 on 2023-03-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("charge", "0009_statprofile_op"),
    ]

    operations = [
        migrations.AddField(
            model_name="statprofile",
            name="loc",
            field=models.CharField(default="", max_length=100),
        ),
    ]
