# Generated by Django 4.1.4 on 2023-01-01 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_wallet_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
