# Generated by Django 4.1.4 on 2023-01-01 13:54

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_delete_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(default=0)),
                ('wid', models.CharField(default=user.models.generate_unique_code, max_length=8, unique=True)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
