# Generated by Django 4.1.4 on 2023-01-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='first_name',
            field=models.CharField(default='first_name', max_length=800),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_name',
            field=models.CharField(default='last_name', max_length=800),
        ),
    ]
