# Generated by Django 4.1.4 on 2023-01-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_wallet_first_name_wallet_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='first_name',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='last_name',
            field=models.CharField(default='', max_length=800),
        ),
    ]
