# Generated by Django 4.1.4 on 2023-01-14 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_wallet_first_name_wallet_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='mo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='first_name',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='last_name',
            field=models.CharField(default='', max_length=800),
        ),
    ]
