# Generated by Django 4.1.4 on 2023-01-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_wallet_first_name_alter_wallet_last_name'),
        ('user', '0007_remove_wallet_mo'),
    ]

    operations = [
    ]
